<a href="https://colab.research.google.com/github/VarnitaJoshi/DeepLearning_Pytorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello")

hello


In [2]:
!nvidia-smi

Sat May  6 09:50:46 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.0.0+cu118


## Introduction to Tensors
Creating Tensors

PyTorch Tensors are created using torch.Tensor()' -= https://pytorch.org/docs/stable/tensors.html




In [4]:
#scalar
scalar= torch.tensor(7)
scalar

tensor(7)

In [5]:
#scalar no dimensions single number
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

Picture-https://www.google.com/url?sa=i&url=https%3A%2F%2Fhadrienj.github.io%2Fposts%2FDeep-Learning-Book-Series-2.1-Scalars-Vectors-Matrices-and-Tensors%2F&psig=AOvVaw3BQMiX9BHI0lk9SpQvMpmG&ust=1683363807016000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCPDM3__o3f4CFQAAAAAdAAAAABAE

In [7]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
#dimension is number of square brackets
vector.ndim

1

In [9]:
#shape of vector
vector.shape

torch.Size([2])

In [10]:
#MATRIX
MATRIX= torch.tensor([[7,8],[9,10],[7,6]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10],
        [ 7,  6]])

In [11]:
#two brackets pairing on outside
MATRIX.ndim


2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([3, 2])

In [14]:
#Tensor
Tensor= torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
Tensor.ndim

3

In [16]:
Tensor.shape
# size= no. elements in last bracket, no. elements in inner bracket,no. elemnts in innermost bracket.

torch.Size([1, 3, 3])

In [17]:
newtensor=torch.tensor([[[1,2],[2,3],[4,5],[6,6]]])
newtensor

tensor([[[1, 2],
         [2, 3],
         [4, 5],
         [6, 6]]])

In [18]:
newtensor.ndim

3

Scalar and vectors lower case
matrix and tensor upper case

In [19]:
newtensor.shape


torch.Size([1, 4, 2])

### RANDOM TENSORS 
WHY?
 a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

Torch Random Tensors-https://pytorch.org/docs/stable/generated/torch.rand.html



In [20]:
# create a random tensors of size/shape (3,4)
random_tensor=torch.rand(3,4)
#random_tensor=torch.rand(1,10,10)
random_tensor


tensor([[0.7580, 0.1873, 0.0186, 0.4626],
        [0.9215, 0.1823, 0.9803, 0.6382],
        [0.4261, 0.2345, 0.7337, 0.0112]])

In [21]:
random_tensor.ndim

2

In [22]:
#random tensor with similar shape to an image tensor, can use size parameter optional
random_image_size_tensor=torch.rand(size=(224,224,3)) # height, width, colour channels (R, G, B)
random_image_size_tensor=torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

###Zeroes and ones

In [23]:
#Create a tensor of all zeroes, used to mask out some columns in a tensor.
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros *random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype # default datatype.

torch.float32

In [27]:
random_tensor.dtype

torch.float32

#### Creating a range of Tensors and tensors-like

In [28]:
#use torch range gets deprecated msg
# one_to_ten=torch.arange(1, 11) see torch.arange
# one_to_ten=torch.arange(start=0, end=1000, step=77)
one_to_ten=torch.arange(start=1, end=11, step=1)

one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# create tensors like--same shape 
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of 3 major error prone area with PyTorch and deep learning.
1. Tensor incorrect datatype
2.Tensor incorrect shape
3. Tensor incorrect device.

Precision in Computing-https://en.wikipedia.org/wiki/Precision_(computer_science)

In [30]:
#Float 32 tensor(precision in computing)
# float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None)
float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None, # datatype of tensor
                          device=None, # device on which tensor is made
                             requires_grad=False) # whether or not to trak gradients for tensor oerations
# float_32_tensor=torch.tensor([3.0,6.0,9.0],dtype=None, device="cuda", requires_grad=False)

                            
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [31]:
float_16_tensor2=torch.tensor([3.0,6.0,9.0],dtype=torch.float16)
float_16_tensor2, float_16_tensor2.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [32]:
float_16_tensor=float_16_tensor2.type(torch.float32)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [33]:
float_32_tensor * float_16_tensor2 # some but not all operations may run ito error when tensors are not of right datatype

tensor([ 9., 36., 81.])

In [34]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [35]:
long_tensor_32=torch.tensor([3,6,9],dtype=torch.long)
long_tensor_32

tensor([3, 6, 9])

In [36]:
# float_32_tensor * int_32_tensor
float_32_tensor * long_tensor_32

tensor([ 9., 36., 81.])

###Getting information from tensors(tensor attributes)

    1. Tensor incorrect datatype-- to get datatype from a tensor, can use 'tensor.dtype'
    2. Tensor incorrect shape-- to get shape from a tensor, use 'tensor.shape'
    3. Tensor incorrect device--to get device from a tensor, use 'tensor.device'




In [37]:
#create tensor   
#s_tensor.size() and s_tensor.shape would give the same thing.
s_tensor=torch.rand(3,4)
s_tensor

tensor([[0.6880, 0.0352, 0.4284, 0.0326],
        [0.6408, 0.5253, 0.6924, 0.5851],
        [0.5186, 0.2463, 0.5513, 0.6960]])

In [38]:
# find details about s_tensor
print(s_tensor)
print(f"Datatype of tensor: {s_tensor.dtype}")
print(f"Shape of tensor: {s_tensor.shape}")
print(f"Device tensor is on: {s_tensor.device}")


tensor([[0.6880, 0.0352, 0.4284, 0.0326],
        [0.6408, 0.5253, 0.6924, 0.5851],
        [0.5186, 0.2463, 0.5513, 0.6960]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###Manipulating Tensors(tensor operations)
tensor operations:

    Addition
    Substraction
    Multiplication (element-wise)
    Division
    Matrix multiplication


In [39]:
#create tensor
tensorr=torch.tensor([1,2,3])
tensorr + 10

tensor([11, 12, 13])

In [40]:
#Multiply tensor by 10
tensorr *10

tensor([10, 20, 30])

In [41]:
tensorr

tensor([1, 2, 3])

In [42]:
#subtract 10
tensorr-10


tensor([-9, -8, -7])

In [43]:
# PyTorch in-built functions
torch.mul(tensorr, 10)


tensor([10, 20, 30])

In [44]:
torch.add(tensorr, 10)

tensor([11, 12, 13])

### Matrix Multiplication
Two ways of multiplication in NN and DL:
1. Element wise
2. Matrix multiplication(dot product)
 More info-https://www.mathsisfun.com/algebra/matrix-multiplying.html

Two rules matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
 *'(3,2) @ (3,2)'  won't work
 * '(2,3) @ (3,2)' will work
 * '(3,2) @ (2,3)' will work
2. The resulting matrix has the shape of the **outer dimensions**:
* '(2,3) @ (3,2)'-> '(2,2)'
* '(3,2) @ (2,3)'->'(3,3)'




In [45]:
# torch.matmul(torch.rand(2,3),torch.rand(3,2))
# torch.matmul(torch.rand(3,2),torch.rand(3,2))
torch.matmul(torch.rand(3,10),torch.rand(10,3))


tensor([[1.8320, 1.8398, 1.5295],
        [2.3229, 3.0681, 2.1241],
        [2.1497, 3.0416, 2.2389]])

In [46]:
#Element wise multiplication.
print(tensorr,"*",tensorr)
print(f"Equals: {tensorr * tensorr}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [47]:
#Matrix Multiplication
torch.matmul(tensorr,tensorr)

tensor(14)

In [48]:
#Matrix Multiplication by hand
1*1+2*2+3*3

14

In [49]:
%%time
value=0
for i in range(len(tensorr)):
    value+=tensorr[i] * tensorr[i]
print(value)





tensor(14)
CPU times: user 490 µs, sys: 0 ns, total: 490 µs
Wall time: 506 µs


In [50]:
%%time
torch.matmul(tensorr,tensorr)

CPU times: user 39 µs, sys: 5 µs, total: 44 µs
Wall time: 47.9 µs


tensor(14)

###One of the most common errors in DL: Shape Errors

In [52]:
# Shapes for matrix multiplication
tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
tensor_B=torch.tensor([[7,10],[8,11],[9,12]])

torch.mm(tensor_A,tensor_B)#torch.mm is same as torch.matmul(alias)



RuntimeError: ignored

In [53]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

#To fix tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**
 **transpose** switches the axes or dimensions of a given tensor.

In [54]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [55]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [56]:
tensor_B.T.shape

torch.Size([2, 3])

In [57]:
# The matrix multiplication operation works when tensor_B is transposed.
print(f"Original shapes: tensor_A={tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"New shapes: tensor_A={tensor_A.shape} (same shape as above), tensor_B={tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape}<- inner dimensions must match")
print("Output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape:{output.shape}")
torch.matmul(tensor_A,tensor_B.T).shape

Original shapes: tensor_A=torch.Size([3, 2]),tensor_B=torch.Size([3, 2])
New shapes: tensor_A=torch.Size([3, 2]) (same shape as above), tensor_B=torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3])<- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape:torch.Size([3, 3])


torch.Size([3, 3])

##Finding the min,max,mean, sum, etc(tensor aggregation)

In [58]:
#Create a tensor
ten1=torch.arange(1, 100, 10)
ten1, ten1.dtype


(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [59]:
torch.min(ten1),ten1.min()

(tensor(1), tensor(1))

In [60]:
#Find the max
torch.max(ten1),ten1.max()

(tensor(91), tensor(91))

In [61]:
#Find the mean
# torch.mean(ten1) this will give datatype error mean cannot work with long requires float32 datatype
torch.mean(ten1.type(torch.float32)), ten1.type(torch.float32).mean()


(tensor(46.), tensor(46.))

In [62]:
#Find the sum
torch.sum(ten1),ten1.sum()

(tensor(460), tensor(460))

##Finding the positional min and max

In [63]:
ten1

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [64]:
ten1.argmin() #returns the index position of target where the minimum value occurs.

tensor(0)

In [65]:
ten1[0]

tensor(1)

In [66]:
#position in tensor thta has the maximum value.
ten1.argmax()

tensor(9)

In [67]:
ten1[9]

tensor(91)

###Resshaping, stacking,squeezing and unsqueezing tensors

*Reshaping - Reshapes an input tensor to a defined shape.

*View- Return a view of an input tensor of certain shape but keep the same memory as the original tensor.

*Stacking- combine multiple tensors on top of each other(vstack) or side by side(hstack)

*Squeeze -removes all '1' dimensions from a tensor

*Unsqueeze- add a '1' dimension to a target tensor.

*Permute- returns a view of the input with dimensions permuted(swapped) in a certain way




In [68]:
#Create a tensor
import torch
t=torch.arange(1,11)
t,t.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [69]:
#Add an extra dimension,reshape has to be compatible with the original size.
# t_reshaped=t.reshape(1,7) this will produce error squeezing 9 elements into a tensor of size 7
# t_reshaped=t.reshape(1,9) # single dimension gets added.
t_reshaped=t.reshape(10,1)
t_reshaped, t_reshaped.shape



(tensor([[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10]]),
 torch.Size([10, 1]))

In [70]:
t_reshaped2=t.reshape(5,2)
t_reshaped2, t_reshaped.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([10, 1]))

In [71]:
import torch
t1=torch.arange(1,10)
t1,t1.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [72]:
t1_reshaped=t1.reshape(1,9)
t1_reshaped,t1_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [73]:
#Change the view --z is just different view of t1---view similar to reshape. View shares the memory with the original tensor.
z=t1.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

## Python slicing w3c.

In [74]:
# Changing z changes x(because a view of a tensor shares the same memory as the orignal input)
z[:,0]=5
z,t1 # both gets changed.

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [75]:
# Stack tensors on top of each other.
t1_stacked= torch.stack([t1,t1,t1,t1],dim=0)
t1_stacked




tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [76]:
### vstack means dimension=0 and hstack means dimension is 1.

In [77]:
#torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor:{t1_reshaped}")
print(f"Previous shape: {t1_reshaped.shape} ")
#remove extra dimensions from t1_reshaped
t1_squeezed=t1_reshaped.squeeze()
print(f"\nNew tensor: {t1_squeezed}")
print(f"New shape:{t1_squeezed.shape}")


# t1_reshaped,t1_reshaped.shape

Previous tensor:tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9]) 

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape:torch.Size([9])


In [78]:
# t1_reshaped.squeeze()

In [79]:
# t1_reshaped.squeeze().shape # squeeze remove all 1s i.e. single dimensions

In [80]:
# torch.unsqueeze()-- adds a single dim to a target tensor at a secific dim(dimension)
print(f"Prevoius target: {t1_squeezed}")
print(f"Previous shape: {t1_squeezed.shape}")

# Add an extra dimension with unsqueeze

t1_unsqueezed= t1_squeezed.unsqueeze(dim=0)
print(f"\n New tensor:{t1_unsqueezed}")
print(f"New shape: {t1_unsqueezed.shape}")





Prevoius target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

 New tensor:tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [81]:
# torch.unsqueeze()-- adds a single dim to a target tensor at a secific dim(dimension)
print(f"Prevoius target: {t1_squeezed}")
print(f"Previous shape: {t1_squeezed.shape}")

# Add an extra dimension with unsqueeze

t2_unsqueezed= t1_squeezed.unsqueeze(dim=1)
print(f"\n New tensor:{t2_unsqueezed}")
print(f"New shape: {t2_unsqueezed.shape}")

Prevoius target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

 New tensor:tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
New shape: torch.Size([9, 1])


In [82]:
# torch.permute rearanges the dimensions of a target tensor in a specified order
t_original=torch.rand(size=(224,224,3)) #[height,width,colour_channels]

#Permute the original tensor to rearrange the axis(or dim) order
t_permuted=t_original.permute(2,0,1) # it takes series of dims. shifts axis 0->1,1->2,2->0

print(f"Previous shape:{t_original.shape}")
print(f"New shape: {t_permuted.shape}") #[colour channels,height,width]

# t_permuted will share the same place in memory as t_original.




Previous shape:torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [83]:
t_original[0,0,0]=898

t_permuted[0,0,0],t_original[0,0,0] # same value gets copied.

(tensor(898.), tensor(898.))

### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy.

In [84]:
# create a tensor
import torch
ti=torch.arange(1,10).reshape(1,3,3) # 1*3*3=9
ti,ti.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [85]:
#index on our new tensor
ti[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [86]:
#index on middle bracket(dim=1)
ti[0][0]


tensor([1, 2, 3])

In [87]:
#index on the most inner bracket(last dimension)
ti[0][0][1]

tensor(2)

In [89]:
ti[1][1][1] #only 1 dimension

IndexError: ignored

In [90]:
ti[0][1][1]

tensor(5)

In [91]:
ti[0][2][2]

tensor(9)

In [92]:
# can use semicolon ":" to select "all" of a target dimension
ti[:,0],ti[:,1]

(tensor([[1, 2, 3]]), tensor([[4, 5, 6]]))

In [93]:
#Get all values of 0th dimension and 1st dimension but only index 1 of 2nd dimension
ti[:,:,1]  


tensor([[2, 5, 8]])

In [94]:
#get all values of 0 dimension but only the 1 index value of 1st and 2nd dimension.
ti[:,1,1]
#ti[0,1,1]

tensor([5])

In [95]:
#get index 0 of 0th and 1st dimension and all values of 2nd dimension.
ti[0, 0, :]

tensor([1, 2, 3])

In [96]:
#index on ti to reurn 9
# ti[0][2][2]
ti[0,2,2]

tensor(9)

In [97]:
#index on x to return 3,6,9
ti[:,:,2]

tensor([[3, 6, 9]])

###PyTorch Tensors and NumPy
NumPy is a popular scientific Python numerical computing library.
And because of this PyTorch has functionality to interact with it.

* Data in NumPy to convert into PyTorch tensor-> 'torch.from_numpy(ndarray)'
* PyTorch tensor -> NumPy -> 'torch.Tensor.numpy()'




In [98]:
#Numpy array to tensor
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array) # warning: when converting from numpy-> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise. 
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [99]:
array.dtype,tensor.dtype

(dtype('float64'), torch.float64)

In [100]:
torch.arange(1.0,8.0).dtype # pyTorch's default datatype is not float 64.

torch.float32

In [101]:
#change value of array, what will it do tensor.
array=array+1 #adding 1 to every value in the array.
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [102]:
#Tensor to NumPy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [103]:
#Change the tensor, what happens to 'numpy_tensor'?
tensor=tensor+1
tensor, numpy_tensor # both do not share memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducubility(trying to take random out of random)

How a Neural Network learns:

'start with random numbers -> tensor operations -> try to make better (again and again and again)'

To reduce randomness in neural networks and PyTorch comes the concept of a **random seed**.

Random seed "flavour the randomness.


In [104]:
import torch
#create two random tensors
rand_tens_A=torch.rand(3,4)
rand_tens_B=torch.rand(3,4)
print(rand_tens_A)
print(rand_tens_B)
print(rand_tens_A==rand_tens_B)



tensor([[0.5659, 0.1416, 0.0949, 0.5004],
        [0.3380, 0.5663, 0.3954, 0.8292],
        [0.7028, 0.0104, 0.9891, 0.8602]])
tensor([[0.7096, 0.6587, 0.9737, 0.5603],
        [0.9171, 0.3116, 0.6750, 0.3901],
        [0.6492, 0.9086, 0.1659, 0.9326]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


Extra resources for reproducibilty-https://pytorch.org/docs/stable/notes/randomness.html

Random seed- wikipedia

In [105]:
#make some random but reproducible tensors
import torch

#set the random seed
Random_seed=27
torch.manual_seed(Random_seed) # works for one block of code.
random_tens_C=torch.rand(3,4)
torch.manual_seed(Random_seed)
random_tens_D=torch.rand(3,4)
print(random_tens_C)
print(random_tens_D)
print(random_tens_C==random_tens_D)




tensor([[0.9847, 0.0852, 0.5334, 0.2196],
        [0.2617, 0.7972, 0.2088, 0.4545],
        [0.1455, 0.2249, 0.7409, 0.2881]])
tensor([[0.9847, 0.0852, 0.5334, 0.2196],
        [0.2617, 0.7972, 0.2088, 0.4545],
        [0.1455, 0.2249, 0.7409, 0.2881]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Running Tensors and  PyTorch Objects on GPUs (and making faster computations)
GPUs= faster computatin on nmbers,  cuda+ Nvidia hardware+PyTorch




### 1. Getting a GPU
1. Easiest- use colab for free gpu(can upgrade)
2. use your own GPU
3. use cloud computing-GC, AWS, Azure.



In [107]:
!nvidia-smi

Sat May  6 09:52:31 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

###Check for GPU access with PyTorch


In [110]:
#check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [112]:
# Setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [113]:
#Count number of devices
torch.cuda.device_count()



1

PyTorch capable of running compute on GPU or CPU, best is t setup device agnostc code:
https://pytorch.org/docs/stable/notes/cuda.html

## Putting tensors (and models) on the GPU

As using a GPU results in faster computations.


In [116]:
#Create a tensor (default on CPU)
tensor=torch.tensor([1,2,3], device="cpu")

#Tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [118]:
#Move tensor to GPU(IF AVAILABLE)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

###Moving Tensors back to CPU

In [119]:
# If tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy() # device issues.

TypeError: ignored

In [121]:
# first shift tensor back to cpu
tensor_back_on_cpu= tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [124]:
tensor_on_gpu # remains unhanged

tensor([1, 2, 3], device='cuda:0')